name: dco_dco_app
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter


  # cached_network_image: ^3.4.1
  # cupertino_icons: ^1.0.8
  # dio: ^5.9.0
  # easy_localization: ^3.0.8
  # firebase_core: ^4.1.0
  # flutter_bloc: ^9.1.1
  # flutter_native_splash: ^2.4.6
  # flutter_screenutil: ^5.9.3
  # flutter_secure_storage: ^9.2.4
  # flutter_svg: ^2.2.0
  # freezed: ^3.2.0
  # freezed_annotation: ^3.1.0
  # get_it: ^8.2.0
  # intl: ^0.20.2
  # json_annotation: ^4.9.0
  # json_serializable: ^6.11.0
  # pretty_dio_logger: ^1.4.0
  # retrofit: ^4.7.2
  # retrofit_generator: ^10.0.2
  # shared_preferences: ^2.5.3
  # shimmer: ^3.0.0


dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
